    #redis设置
    redis:
      prefix: dev
      cluster:
        max-redirects: 3
        nodes:
          - redis-cluster-bigdata-01.qiandingyun.com:6378
          - redis-cluster-bigdata-02.qiandingyun.com:6378
          - redis-cluster-bigdata-03.qiandingyun.com:6378
          - redis-cluster-bigdata-04.qiandingyun.com:6378
          - redis-cluster-bigdata-05.qiandingyun.com:6378
          - redis-cluster-bigdata-06.qiandingyun.com:6378
      database: 0
      lettuce:
          pool:
              max-active: 20
              max-idle: 10
              max-wait: 6000
              min-idle: 5
      timeout: 1000
